Add drag and drop with tasks status feature
alonsofl/todo-list pull request #3
Opened 2021-07-15 20:08 UTC by alonsofl

### Summary
Add drag and drop (this feature updates the tasks index automatically) and completed/uncompleted features.

#### Details
- Added modules for each functionality.
- Added drag and drop script.
- Added script to automatically update the index for each task when moving tasks.
- Added clear completed tasks script.

2021-07-15 21:34 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello @alonsofl :wave:

_Your project is coming up well :+1:
You've been professionally consistent with your commit messages and you've also used descriptive PR title and summary :clap:
Your Linter checks are all passing with no errors :100:_

__However, you need to make some required changes before moving on to the next assignment.__
> Keep in mind that your long hours of work are appreciated. However, the code review process is for improving the code you wrote, and not for criticizing it :blush: 

### **Required Changes** :recycle: 
Check the comments under the review.

### **Optional Changes** :zap: 
N/A


* * *
**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. You can mention me (@teekaytech) so I can be notified about your comments and respond._

*REMINDER: As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).*

_**Please make the required changes and submit another review request when you are done.**_

* * *

_Reviewed by:_ [**Taofeek Olalere**](https://github.com/teekaytech)
__Cheers & Happy coding :smiley:__

2021-07-15 21:34 UTC, teekaytech commented on src/modules/dynamic-list.js
> +}
- [ ] These drag features seem not to be working, as I was unable to reorder the list by dragging each item and moving it into the desired position. I added a gif image of my experience when I tried to drag. You can also see the error message in the console, which I think may help. Kindly fix this.
![drag](https://user-images.githubusercontent.com/26856491/125860163-67b1c15e-e6af-4b7c-8e00-abbb08665877.gif)

- [ ] The task object's values for `index` are updated upon user drag actions. This implies that when an item is dragged, the `index` of such item is updated to the new position it represents. Other books' indexes are also updated accordingly.

2021-07-15 22:04 UTC, alonsofl commented on src/modules/dynamic-list.js
> +}
Hello, @teekaytech! Thanks for your review and your time :smiley: 
Actually, I applied the drag event listeners to the LI items, I was looking for information about how to apply the event listeners to the IMG that you're trying to drag and drag the LI container but didn't found any.
Do you have any suggestions? I would really appreciate it :raised_hands:

2021-07-16 16:13 UTC, teekaytech commented on src/modules/dynamic-list.js
> +}
> Hello, @teekaytech! Thanks for your review and your time 
> Actually, I applied the drag event listeners to the LI items, I was looking for information about how to apply the event listeners to the IMG that you're trying to drag and drag the LI container but didn't found any.
> Do you have any suggestions? I would really appreciate it

Hello @alonsofl,
It is not compulsory that the drag event be applied to the image. As long as the drag event works fine on the list item, we should be good to go. If that's the case, you can request another review. Thank you for letting me know.

Happy coding!

2021-07-16 18:34 UTC, Davidosky007 requested changes
## Hi @alonsofl 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![almost git](https://user-images.githubusercontent.com/52497246/125993439-b6671eec-03dd-457e-9400-14852ee8024e.gif)

 ## Required Changes ♻️
## _Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-07-16 18:34 UTC, Davidosky007 commented on src/modules/dynamic-list.js
> +}
* Good job 💪 implementing changes requested by the previous reviewer 👏 
* one more issue left 🙏 the index of the object values are not updated in the local storage. [Please refer back to the project requirement](https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/m2_interactive_list.md#:~:text=Update%20items%20object%27s%20values%20for%20index%20and%20completed%20keys%20upon%20user%20actions.)

2021-07-16 19:02 UTC, alonsofl commented
@Davidosky007 the change that you're requesting it's already solved.

2021-07-16 19:04 UTC, Davidosky007 commented
> @Davidosky007 the change that you're requesting it's already solved.
* Good job implementing it 👍 
* you can submit for review next reviewer would know to approve 👍

2021-07-16 19:53 UTC, smcommits requested changes
Hi <STUDENT_MENTION>, 

### You have done a great job so far!
### However, the issue raised by the previous reviewer is still persistent. Let us try to fix it together. 

 ## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

---
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-07-16 19:53 UTC, smcommits commented on src/modules/dynamic-list.js
> +  list.addEventListener('drop', (ev) => {
- [ ] **The drop functionality is still now working. Please fix this.**

As mentioned by the previous reviewer, the drop functionality is still not working.

![ev](https://user-images.githubusercontent.com/59168430/126000503-fb63c51e-26cf-4846-84aa-ad009a2c0bcd.gif)

As you can see, upon dropping the element, we get an error, and drop functionality doesn't work. I suspect the problem is in the module `drag-and-drop.js`. I have highlighted the problem in an inline comment with the tag **[Source of Bug]**. 


- [ ] **Please make sure the `index` of the task is changed in local storage.**

After you fix the drop functionality, please make sure that when someone drags and drops any task in the list, the index of that particular task is also changed in the local storage.

2021-07-16 19:53 UTC, smcommits commented on src/modules/drag-and-drop.js
> +    const parentElement = ev.path[1];
- [ ] **[Source of Bug] I suspect that the drop functionality is not working due to this line of code.**

Firstly, the `ev` here is the event itself not the target. So, the `ev` here will be the drop event. Secondly, neither the event nor its target has any method named `path`. Hence, the error. 

If I understand this correctly, what you are trying to do can be achieved by replacing this line of code with the following:

```JS
const parentElement  = ev.target.parentNode 
```
This will return the parent of the `li` element that is clicked. I think this will fix the drop functionality.

2021-07-16 19:56 UTC, alonsofl commented on src/modules/drag-and-drop.js
> +    const parentElement = ev.path[1];
@smcommits neither of the reviewers saw that.
As you saw @Davidosky007 made a mistake. I literally didn't change anything on the project because I was on a call with him and we saw together that the project is working.

2021-07-16 20:23 UTC, Spayco commented
Hello 👋,

This is an additional review as a result of the second opinion request.

I highly recommend fixing the issue reported by @smcommits 

However, since it wasn't asked by the previous reviewer, those should've been optional

As this was the only reason that your project was not approved it will be approved as soon as possible.

Keep rocking 🚀!

2021-07-16 21:40 UTC, alonsofl commented
> Hello ,
> 
> This is an additional review as a result of the second opinion request.
> 
> I highly recommend fixing the issue reported by @smcommits
> 
> However, since it wasn't asked by the previous reviewer, those should've been optional
> 
> As this was the only reason that your project was not approved it will be approved as soon as possible.
> 
> Keep rocking !

Hello @Spayco! Thanks for your time.

The button status for the task looks as "incompleted". I only have to wait until it's approved by a reviewer automatically and the button status will change to "Submit" right?

2021-07-17 10:17 UTC, nidalaa commented
Hello @alonsofl,

It will be changed in your Dashboard by our Dev Team before the final deadline. Please consider it approved until that happens :)

2021-07-17 14:01 UTC, alonsofl commented
> Hello @alonsofl,
> 
> It will be changed in your Dashboard by our Dev Team before the final deadline. Please consider it approved until that happens :)

Hello @nidalaa,
Thanks for your answer. So I can merge this branch and continue working?
Appreciate your help.

2021-07-17 14:25 UTC, nidalaa commented
@alonsofl  as @Spayco said:


>I highly recommend fixing the issue reported by @smcommits

>However, since it wasn't asked by the previous reviewer, those should've been optional

>As this was the only reason that your project was not approved it will be approved as soon as possible.


You can merge but an extra effort to implement that change will pay off in the future :)

2021-07-17 20:37 UTC, merged